source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GradientButton_Example' do
    pod "GradientButton", :path => "../"
    pod 'PureLayout'
end

target 'GradientButton_Tests' do
    pod "GradientButton", :path => "../"
    
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
